path: '/Users/kevin/.rbenv/shims:/Users/kevin/.pyenv/shims:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/kevin/bin:/Users/kevin/local/bin:/Users/kevin/src/github.com/jkbrzt/httpie/venv/bin:/Users/kevin/src/github.com/rg3/youtube-dl/venv/bin:/Users/kevin/go/bin:/Users/kevin/.cargo/bin:/usr/local/sbin'
gopath: /Users/kevin

